apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-java
resources:
  - ../../base/sample-java
  - ingress.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: java-webapp
