apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda
resources:
  - ../../base/keda
patches:
  - path: keda-values.yaml
    target:
      kind: HelmRelease
      name: keda
