apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/nginx-deploy
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/replicas
          value: 2
      target:
        kind: Deployment
        name: nginx-deployment