---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 60m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 60m
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
  values:
    installCRDs: true
