---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kafka
  namespace: kafka
spec:
  type: oci
  interval: 60m0s
  url: oci://registry-1.docker.io/bitnamicharts/kafka
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 60m
  chart:
    spec:
      chart: kafka
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kafka
      interval: 12h
  # https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
  values:
    controller:
      replicaCount: 1
      controllerOnly: false
      