---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
  interval: 50m
  install:
    remediation:
      retries: 3