---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 60m0s
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 60m
  chart:
    spec:
      chart: kyverno
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 12h
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml
  values:
    crds:
      install: true
    config:
      create: true
      webhooks:
        - namespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kyverno
    metricsConfig:
      create: true
      namespaces:
        include: []
        exclude: ["kube-system", "kyverno"]
    admissionController:
      container:
        resources:
          limits:
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi