apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
  interval: 50m
  install:
    remediation:
      retries: 3